version: '3.3'
services:
  aioracle_api_prod_request:
    image: devorai/ai-oracle-prod-request:0.0.3
    container_name: aioracle_api_prod_request
    env_file:
      - ./.env
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    networks:
      - orai-network

  aioracle_db_prod_request:
    container_name: aioracle_db_prod_request
    image: mariadb:10.7.4
    environment:
      MYSQL_DATABASE: 'oracle_prod_request'
      MYSQL_USER: 'orai'
      MYSQL_PASSWORD: 'userxxx'
      MYSQL_ROOT_PASSWORD: 'rootxxx'
    volumes:
      - '../../../../data_prod/db_prod_request/:/var/lib/mysql'
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - orai-network


networks:
  orai-network:
    external: false
    name: orai-network
