/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.27.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient } from "@cosmjs/cosmwasm-stargate";
import {HandleMsg, HumanAddr, Uint128, StateMsg, Coin, InitMsg, State} from "./types";
import {QueryMsg} from "./DsourceEmpty.types";
export interface DsourceEmptyReadOnlyInterface {
  contractAddress: string;
  getState: () => Promise<GetStateResponse>;
  getOwner: () => Promise<GetOwnerResponse>;
}
export class DsourceEmptyQueryClient implements DsourceEmptyReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;

  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.getState = this.getState.bind(this);
    this.getOwner = this.getOwner.bind(this);
  }

  getState = async (): Promise<GetStateResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_state: {}
    });
  };
  getOwner = async (): Promise<GetOwnerResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      get_owner: {}
    });
  };
}