/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.27.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./AioracleHealthCheck.types";
import * as _1 from "./AioracleHealthCheck.client";
import * as _2 from "./AioracleServiceFees.types";
import * as _3 from "./AioracleServiceFees.client";
import * as _4 from "./AioracleV2.types";
import * as _5 from "./AioracleV2.client";
import * as _6 from "./DsourceEmpty.types";
import * as _7 from "./DsourceEmpty.client";
import * as _8 from "./OscriptBasic.types";
import * as _9 from "./OscriptBasic.client";
import * as _10 from "./OscriptFlowerClassification.types";
import * as _11 from "./OscriptFlowerClassification.client";
import * as _12 from "./OscriptPrice.types";
import * as _13 from "./OscriptPrice.client";
import * as _14 from "./ProviderBridge.types";
import * as _15 from "./ProviderBridge.client";
import * as _16 from "./TcaseEmpty.types";
import * as _17 from "./TcaseEmpty.client";
import * as _18 from "./TcaseFlowerClassification.types";
import * as _19 from "./TcaseFlowerClassification.client";
export namespace contracts {
  export const AioracleHealthCheck = { ..._0,
    ..._1
  };
  export const AioracleServiceFees = { ..._2,
    ..._3
  };
  export const AioracleV2 = { ..._4,
    ..._5
  };
  export const DsourceEmpty = { ..._6,
    ..._7
  };
  export const OscriptBasic = { ..._8,
    ..._9
  };
  export const OscriptFlowerClassification = { ..._10,
    ..._11
  };
  export const OscriptPrice = { ..._12,
    ..._13
  };
  export const ProviderBridge = { ..._14,
    ..._15
  };
  export const TcaseEmpty = { ..._16,
    ..._17
  };
  export const TcaseFlowerClassification = { ..._18,
    ..._19
  };
}
export * from "./types";