version: '3.3'
services:
  aioracle_server:
    container_name: aioracle_server
    image: orai/aioracle-server:0.0.1
    working_dir: /workspace
    # tty: true
    restart: on-failure
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 8080:8080
    cap_add:
      - SYS_PTRACE
    env_file:
      - .env
