version: '3.3'
services:

  mongodb_container:
    image: mongo # https://hub.docker.com/_/mongo
    env_file:
      - .env.mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: $ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $ROOT_PASSWORD
    command: --noscripting # disable JS scripting (because we dont use JS code in mongo ops)
    ports:
      - 27017:27017
    logging:
      driver: "local"
      options:
        max-size: "100m"
        max-file: "2"
    volumes:
      - mongodb_data_container:/data/db

  aioracle_server:
    container_name: aioracle_server
    image: orai/aioracle-server:0.0.2
    working_dir: /workspace
    restart: on-failure
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 8080:8080
    cap_add:
      - SYS_PTRACE
    env_file:
      - .env
    logging:
      driver: "local"
      options:
        max-size: "100m"
        max-file: "2"
    depends_on:
      - mongodb_container
      - elasticsearch

  elasticsearch:
    build:
      context: ../../docker-elk/elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ../../docker-elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
      - elasticsearch:/usr/share/elasticsearch/data:z
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: $ELASTIC
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - elk

  kibana:
    build:
      context: ../../docker-elk/kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ../../docker-elk/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,z
    ports:
      - "5601:5601"
    environment:
      - KIBANA_SYSTEM=$KIBANA_SYSTEM
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge

volumes:
  mongodb_data_container:
  elasticsearch:
