version: '3.3'
services:
  aioracle_server_mainnet:
    image: oraichain/foundation-aioracle-server:0.0.5
    working_dir: /workspace
    restart: on-failure
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - SYS_PTRACE
    logging:
      driver: gelf
      options:
        gelf-address: foo
        tag: "aioracle-server"
    environment:
      - NODE_ENV=mainnet
      - MONGO_URL=
      - CONTRACT_ADDRESS=orai19aczly33fr3s23030qeu0dexyu8vcrwwdpva9v
      - NETWORK_LCD=https://lcd.orai.io
      - CHAIN_ID=Oraichain
      - NETWORK_RPC=https://rpc.orai.io
      - MNEMONIC=
      - PORT=8080
      - HOST=0.0.0.0
      - WS_PORT=7071
    depends_on:
      - mongodb_container
    deploy:
      replicas: 1
      placement: 
        constraints: 
          - node.labels.name == worker2
    networks:
      - net
      - default
 
  mongodb_container:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME:bar
      MONGO_INITDB_ROOT_PASSWORD:foo
    volumes:
      - mongodb_data_container:/data/db
    deploy:
      replicas: 1
      placement: 
        constraints: 
          - node.labels.name == worker2

networks:
  net:
    external:
      name: portainer_default

volumes:
  mongodb_data_container: