version: '3.3'
services:

  mongodb_container:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: $ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $ROOT_PASSWORD
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  aioracle_server:
    container_name: aioracle_server
    image: orai/aioracle-server:0.0.1
    working_dir: /workspace
    # tty: true
    restart: on-failure
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 8080:8080
    cap_add:
      - SYS_PTRACE
    env_file:
      - .env
    depends_on:
      - mongodb_container

volumes:
  mongodb_data_container:
