version: '3.3'
services:
  aioracle_api_stg:
    image: devorai/ai-oracle-staging:0.0.4
    container_name: aioracle_api_stg
    env_file:
      - ./.env
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    restart: always
    networks:
      - orai-network

  aioracle_db_stg:
    container_name: aioracle_db_stg
    image: mariadb:10.7.4
    environment:
      MYSQL_DATABASE: 'ai_oracle'
      MYSQL_USER: 'orai'
      MYSQL_PASSWORD: 'userxxx'
      MYSQL_ROOT_PASSWORD: 'rootxxx'
    volumes:
      - '../../../../data_staging/maria-db/:/var/lib/mysql'
    restart: always
    networks:
      - orai-network
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci


networks:
  orai-network:
    external: false
    name: orai-network
