version: '3.3'
services:
  ai_executor_interval_prod:
    image: orai/aioracle-server:0.0.3
    container_name: ai_executor_interval_prod
    restart: on-failure
    env_file:
      - ../../.env
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 7071:7071
    cap_add:
      - SYS_PTRACE
    networks:
      - elk
    command: node dist/commander interval

networks:
  elk:
    driver: bridge
    external: true
    name: elk
