/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.27.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient } from "@cosmjs/cosmwasm-stargate";
import {} from "./types";
import {AggregateResponse, ExecuteMsg, InstantiateMsg, QueryMsg} from "./OscriptFlowerClassification.types";
export interface OscriptFlowerClassificationReadOnlyInterface {
  contractAddress: string;
  aggregate: ({
    results
  }: {
    results: string[];
  }) => Promise<AggregateResponse>;
}
export class OscriptFlowerClassificationQueryClient implements OscriptFlowerClassificationReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;

  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.aggregate = this.aggregate.bind(this);
  }

  aggregate = async ({
    results
  }: {
    results: string[];
  }): Promise<AggregateResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      aggregate: {
        results
      }
    });
  };
}