version: "3.8"

services:
  mongo1:
    container_name: mongo1
    image: mongo
    volumes:
      - mongo1_vol:/data/db
      - ./mongod.conf:/etc/mongod.conf
      - ./replicaKeyFile:/etc/replicaKeyFile
      - ./rs-init.sh:/scripts/rs-init.sh
    networks:
      - mongors-network
    logging:
      driver: "local"
      options:
        max-size: "100m"
        max-file: "2"
    ports:
      - 27021:27017
    links:
      - mongo2
      - mongo3
    # restart: always
    entrypoint:
      [
        "/usr/bin/mongod",
        "--bind_ip_all",
        "--noscripting",
        "--config",
        "/etc/mongod.conf",
      ]

  mongo2:
    container_name: mongo2
    image: mongo
    volumes:
      - mongo2_vol:/data/db
      - ./mongod.conf:/etc/mongod.conf
      - ./replicaKeyFile:/etc/replicaKeyFile

    networks:
      - mongors-network
    logging:
      driver: "local"
      options:
        max-size: "100m"
        max-file: "2"
    ports:
      - 27022:27017
    # restart: always
    entrypoint:
      [
        "/usr/bin/mongod",
        "--bind_ip_all",
        "--noscripting",
        "--config",
        "/etc/mongod.conf",
      ]

  mongo3:
    container_name: mongo3
    image: mongo
    volumes:
      - mongo3_vol:/data/db
      - ./mongod.conf:/etc/mongod.conf
      - ./replicaKeyFile:/etc/replicaKeyFile
    networks:
      - mongors-network
    logging:
      driver: "local"
      options:
        max-size: "100m"
        max-file: "2"
    ports:
      - 27023:27017
    # restart: always
    entrypoint:
      [
        "/usr/bin/mongod",
        "--bind_ip_all",
        "--noscripting",
        "--config",
        "/etc/mongod.conf",
      ]

  mongo4:
    container_name: mongo4
    image: mongo
    volumes:
      - mongo4_vol:/data/db
      - ./mongod.conf:/etc/mongod.conf
      - ./replicaKeyFileWrong:/etc/replicaKeyFile
    networks:
      - mongors-network
    logging:
      driver: "local"
      options:
        max-size: "100m"
        max-file: "2"
    ports:
      - 27024:27017
    # restart: always
    entrypoint:
      [
        "/usr/bin/mongod",
        "--bind_ip_all",
        "--noscripting",
        "--config",
        "/etc/mongod.conf",
      ]

volumes:
  mongo1_vol:
  mongo2_vol:
  mongo3_vol:
  mongo4_vol:

networks:
  mongors-network:
    driver: bridge
