version: '3.3'
services:
  aioracle_mongodb_container:
    image: mongo
    env_file:
      - .env.mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
